"""фото для афиши теперь необязательно

Revision ID: 060dc70e205b
Revises: dac14e7d77e5
Create Date: 2025-03-04 00:52:05.659733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060dc70e205b'
down_revision = 'dac14e7d77e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###
