"""добавила поле даты создания комментария

Revision ID: 4ef26a2b3a6f
Revises: 4de0b6a52a79
Create Date: 2025-03-19 17:55:22.845751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef26a2b3a6f'
down_revision = '4de0b6a52a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
