"""поменяла тип для фото

Revision ID: 55277c212d46
Revises: 060dc70e205b
Create Date: 2025-03-04 00:55:10.647970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55277c212d46'
down_revision = '060dc70e205b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
