"""тип мероприятия

Revision ID: a07196711e8d
Revises: 4ef26a2b3a6f
Create Date: 2025-04-21 19:06:42.072497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07196711e8d'
down_revision = '4ef26a2b3a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_event')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('event_type')

    op.create_table('_alembic_tmp_event',
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('photo', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('link', sa.VARCHAR(length=40), nullable=False),
    sa.Column('city_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.city_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###
